import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/sections/NavBar";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import { NotificationProvider } from "@/context/NotificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NuqsAdapter>
          <NotificationProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <NavBar />
            </Suspense>
            <main
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Toaster position="bottom-right" />
              {children}
            </main>
          </NotificationProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
